name: market

services:
  postgres:
    attach: false
    image: postgres:alpine
    command: -c log_statement=all -p ${DB_PORT}
    ports:
      - '5432:${DB_PORT}'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - market-net

  adminer:
    attach: false
    image: adminer
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - '7777:8080'
    networks:
      - market-net

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    environment:
      DB_HOST: 'postgres'
      DB_PORT: '${DB_PORT}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - postgres
    ports:
      - '80:8080'
    networks:
      - market-net


networks:
  market-net:
    driver: bridge
